<!DOCTYPE html>
<html>
    <head>
        <title><?= $this->escape( $this -> meta_title ) ?></title>
        <meta name="keywords" content="<?= $this->escape( $this -> meta_keywords ) ?>"/> 
        <meta name="description" content="<?= $this->escape( $this -> meta_description ) ?>"/> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="shortcut icon" href="/image/favicon.ico"/>
        <link rel="stylesheet" type="text/css" href="/css/index.css"/>
        <link rel="stylesheet" type="text/css" href="/css/supersized.core.css"/>
        <script type="text/javascript" src="/js/jquery-2.1.3.min.js"></script>
        <script type="text/javascript" src="/js/jquery.form.min.js"></script>
        <script type="text/javascript" src="/js/jquery.simplemodal.1.4.4.min.js"></script>
        <script type="text/javascript" src="/js/supersized.core.3.2.1.min.js"></script>
        <script type="text/javascript" src="/js/jquery.cycle2.min.js"></script>
        <script type="text/javascript" src="/js/jquery.cycle2.carousel.min.js"></script>
        <script type="text/javascript" src="/js/interface.js"></script>
    </head>
    <body>
        <div class="wrapper">
            <div class="header">
                <div class="left">
                    <div class="logo">
                        <a href="/">
                            <img src="/image/bodysolid_logo.png" />
                        </a>
                    </div>
                    <div class="contact">
                        <div class="phone">
                            <p>(495) 518-52-97, (495) 744-61-65</p>
                        </div>
                        <div class="callback">
                            <a href="/callback" title="Обратный звонок" onclick="return callback()">
                                <img src="/image/top_phone.png" />
                            </a>
                        </div>
                        <div class="email">
                            <a href="mailto:andreisport@bodysolid.ru">
                                <img src="/image/top_mail.png" />
                            </a>
                        </div>
                    </div>
                    <div class="menu">
<?= $this->catalogue ?>
                    </div>
                </div>
                <div class="right">
                    <div class="menu">
<?= $this->menu ?>
                    </div>
                    <div class="client">
<?= $this->client ?>
                    </div>
                </div>
            </div>
            <div class="content">
<?php if (isset($this->content)) { ?>
<?= $this->content ?>
<?php } ?>
<?php if (isset($this->left)) { ?>
                <div class="left">
<?= $this->left ?>
                </div>
<?php } ?>
<?php if (isset($this->right)) { ?>
                <div class="right">
<?= $this->right ?>
                </div>
<?php } ?>
            </div>
            <div class="cart">
<?= $this->cart ?>
            </div>
            <div class="compare">
<?= $this->compare ?>
            </div>
            <div class="body-focus">
                <div class="title">
                    <a href="/body_focus">Целевые<br/>мышцы</a>
                </div>
            </div>
            <div class="price-list">
                <div class="title">
                    <a href="/price_list">Прайс-<br/>лист</a>
                </div>
            </div>
            <div class="bottom_25">
                <a class="bottom_25" href="/"><img src="/image/bottom_25.png" /></a>
            </div>
            <div class="footer">
                <div class="search">
<?= $this->search ?>
                </div>
                <div class="copyright">
                    <p>&copy; ООО "Фитнесспорт", 2015 г.</p>
                </div>
            </div>
        </div>
    </body>
</html>
