<?php $cart = Adminko\Cart::factory(); ?>
<?php $compare = Adminko\Compare::factory(); ?>
<div class="left">
    <div class="card-title">
<?php if ($this->client) { ?>
        <div class="favourite">
            <a href="" onclick="return likeItem(<?= $this->product->getId() ?>, this)"<?php if ($this->client->isLike($this->product)) { ?> class="unlike" title="Удалить из Избранного"<?php } else { ?> class="like" title="Добавить в Избранное"<?php } ?>></a>
        </div>
<?php } ?>
        <h1><?= $this->product->getProductArticle() ?></h1>
        <h2><?= $this->product->getProductTitle() ?></h2>
<?php if ($this->client) { ?>
        <p class="status"><?= $this->product->getProductStateTitle() ?></p>
<?php } ?>
    </div>
    <div class="card-image">
        <script type="text/javascript" src="/js/jquery.elevateZoom-3.0.8.min.js" ></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $("#zoom").elevateZoom({zoomWindowWidth: 500, zoomWindowHeight: 330});
            });
        </script>
        <img id="zoom" src="<?= $this->product->getProductImage() ?>/r/180/180" data-zoom-image="<?= $this->product->getProductImage() . '/r/1200/1200' ?>" />
    </div>
<?php if ($this->client) { ?>
    <div class="card-rating">
<?php $rating = round($this->product->getProductRating()); ?>
        <div class="vote<?php if (!$this->client->isVote($this->product)) { ?> enabled<?php } ?>" rating="<?= $rating ?>">
<?php for ($i = 1; $i <= 5; $i++) { ?>
            <div class="star<? if ($rating >= $i) { ?> active<? } ?>" id="<?= $this->product->getId() ?>" mark="<?= $i ?>"></div>
<?php } ?>
        </div>
  </div>
<?php } ?>
    <div class="card-price">
        <?= number_format($this->product->getProductPrice(), 0, '.', ' ') ?> р.
    </div>
    <div class="card-cart<?php if ($cart->in($this->product->getId())) { ?> selected<?php } ?>">
        <a href="/cart" onclick="return buyItem(<?= $this->product->getId() ?>, this)">Купить</a>
    </div>
    <div class="card-compare<?php if ($compare->in($this->product->getId())) { ?> selected<?php } ?>">
        <a href="/compare" onclick="return compareItem(<?= $this->product->getId() ?>, this)">Сравнить</a>
    </div>
</div>
<div class="right">
    <div class="card-tab">
        <a href="" class="card-tab-text selected" for="card-content-text">Описание</a>
        <a href="" class="card-tab-properties" for="card-content-properties">Свойства</a>
        <a href="" class="card-tab-photoes" for="card-content-photoes">Фото</a>
        <a href="" class="card-tab-video" for="card-content-video">Видео</a>
        <a href="" class="card-tab-options" for="card-content-options">Опции</a>
        <a href="" class="card-tab-files" for="card-content-files">Файлы</a>
    </div>
    <div class="card-content">
        <div id="card-content-text" style="display: block" class="noselect">
            <?= $this->product->getProductDescription() ?>
        </div>
        <div id="card-content-properties" style="display: none">
            <ul class="card-list">
<?php   foreach ($this->product->getPropertyList() as $property) { ?>
<?php       if (!is_empty($property->getPropertyValue())) { ?>
                <li>
                    <?= $property->getPropertyTitle() ?>: <?= $property->getPropertyValue() ?> <?= $property->getPropertyUnit() ?>
                </li>
<?php       } ?>
<?php   } ?>
            </ul>
            <h2>Позволяет выполнять упражнения</h2>
            <ul class="card-list">
<?php   foreach ($this->product->getArticleList() as $article) { ?>
                <li>
                    <a href="<?= $article->getArticleUrl() ?>"><?= $article->getArticleTitle() ?></a>
                </li>
<?php   } ?>
            </ul>
        </div>
        <div id="card-content-photoes" style="display: none">
            <script type="text/javascript" src="/js/colorbox/jquery.colorbox-min.js" ></script>
            <link rel="stylesheet" type="text/css" href="/js/colorbox/colorbox.css" />
            <script>
                $(document).ready(function() {
                    $(".fancybox").colorbox({maxWidth: 1200, maxHeight: 600});
                });
            </script>
            <ul class="card-gallery">
<?php foreach ($this->product->getPictureList() as $picture) { ?>
                <li>
                    <a class="fancybox" rel="fancybox" href="<?= $picture->getPictureImage() ?>" title="">
                        <img src="<?= $picture->getPictureImage() . '/r/180/180' ?>" border="0">
                    </a>
                </li>
<?php } ?>
            </ul>
            <div class="clear"></div>
        </div>
        <div id="card-content-video" style="display: none">
<?php foreach ($this->product->getVideoList() as $video) { ?>
            <?= $video->getVideoCode(); ?>
<?php } ?>
        </div>
        <div id="card-content-options" style="display: none">
            <div class="catalogue">
<?php foreach ($this->product->getOptionsList() as $product_item) { ?>
<?= Adminko\View::block('module/product/product', $product_item) ?>
<?php } ?>
                <div class="clear"></div>
            </div>
        </div>
        <div id="card-content-files" style="display: none">
            <ul class="card-list">
<?php foreach ($this->product->getDownloadList() as $download) { ?>
                <li>
                    <a href="<?= $download->getDownloadFile() ?>"><?= $download->getDownloadTitle() ?></a> (<?= format_size($download->getDownloadSize()) ?>)
                </li>
<?php } ?>
            </ul>
        </div>
    </div>
</div>
