<?= Adminko\View::block('module/client/menu') ?>

<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    <label>Имя <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('client_title', $this->client->getClientTitle())) ?>" name="client_title" />
<? if ($this->error['client_title']) { ?>
    <span class="error"><?= $this->error['client_title'] ?></span>
<? } ?>
    <br/>
    <label>E-mail <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('client_email', $this->client->getClientEmail())) ?>" name="client_email" />
<? if ($this->error['client_email']) { ?>
    <span class="error"><?= $this->error['client_email'] ?></span>
<? } ?>
    <br/>
    <label>Телефон <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('client_phone', $this->client->getClientPhone())) ?>" name="client_phone" />
<? if ($this->error['client_phone']) { ?>
    <span class="error"><?= $this->error['client_phone'] ?></span>
<? } ?>
    <br/>
    <label>Контактное лицо <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('client_person', $this->client->getClientPerson())) ?>" name="client_person" />
<?php if ($this->error['client_person']) { ?>
    <span class="error"><?= $this->error['client_person'] ?></span>
<?php } ?>
    <br/>
    <label>Юридический адрес <span class="require">*</span></label><br/>
    <textarea name="client_legal_address"><?= $this->escape($this->fromRequest('client_legal_address', $this->client->getClientLegalAddress())) ?></textarea>
<?php if ($this->error['client_legal_address']) { ?>
    <span class="error"><?= $this->error['client_legal_address'] ?></span>
<?php } ?>
    <br/>
    <label>Фактический адрес</label><br/>
    <textarea name="client_actual_address"><?= $this->escape($this->fromRequest('client_actual_address', $this->client->getClientActualAddress())) ?></textarea>
<?php if ($this->error['client_actual_address']) { ?>
    <span class="error"><?= $this->error['client_actual_address'] ?></span>
<?php } ?>
    <br/>
    <br/>
    <label>Старый пароль</label>
    <input type="password" value="" name="client_password_old" />
<? if ($this->error['client_password_old']) { ?>
    <span class="error"><?= $this->error['client_password_old'] ?></span>
<? } ?>
    <br/>
    <label>Новый пароль</label>
    <input type="password" value="" name="client_password" />
<? if ($this->error['client_password']) { ?>
    <span class="error"><?= $this->error['client_password'] ?></span>
<? } ?>
    <br/>
    <label>Подтверждение</label>
    <input type="password" value="" name="client_password_confirm" />
<? if ($this->error['client_password_confirm']) { ?>
    <span class="error"><?= $this->error['client_password_confirm'] ?></span>
<? } ?>
    <br/>
    <input type="submit" value="Сохранить" />
</form>