<h1>Оформление заказа</h1>
<?php if ($this->cart->getQuantity()) { ?>
<div class="cart-form">
    <table>
        <tr class="title">
            <td class="title name">
                Товар
            </td>
            <td class="title price">
                Цена
            </td>
            <td class="title quantity">
                Количество
            </td>
            <td class="title cost">
                Стоимость
            </td>
        </tr>
<?php 		foreach ($this->cart->get() as $item) { ?>
<?php 			$product = Adminko\Model\Model::factory('product')->get($item->id); ?>
        <tr>
            <td class="name">
                <div class="cart_image_container">
                    <img src="<?= $product->getProductImage() ?>/r/50/50" alt="<?= $product->getProductArticle() ?> - <?= $product->getProductTitle() ?>"/>
                </div>
                <div class="cart_title_container">
                    <a href="<?= $product->getProductUrl() ?>"><?= $product->getProductArticle() ?> <?= $product->getProductTitle() ?></a>
                </div>
            </td>
            <td class="price">
                <?= $item->price ?>
            </td>
            <td class="quantity">
                <?= $item->quantity ?>
            </td>
            <td class="cost">
                <?= $item->quantity * $item->price ?>
            </td>
        </tr>
<?php 		} ?>
        <tr class="total">
            <td class="total name">
                &nbsp;
            </td>
            <td class="total price">
                Итого:
            </td>
            <td class="total quantity">
                <?= $this->cart->getQuantity() ?>
            </td>
            <td class="total cost">
                <?= $this->cart->getSum() ?>
            </td>
            <td class="total delete">
                &nbsp;
            </td>
        </tr>
<?php if ($this->client) { ?>
        <tr class="discount">
            <td class="total name">
                &nbsp;
            </td>
            <td class="total price" colspan="2">
                Ваша скидка:
            </td>
            <td class="total cost">
                <?= round((1 - $this->discount) * 100) ?> %
            </td>
            <td class="total delete">
                &nbsp;
            </td>
        </tr>
        <tr class="final">
            <td class="total name">
                &nbsp;
            </td>
            <td class="total price" colspan="2">
                С учетом скидки:
            </td>
            <td class="total cost">
                <?= round($this->cart->getSum() * $this->discount) ?>
            </td>
            <td class="total delete">
                &nbsp;
            </td>
        </tr>
<?php } ?>
    </table>
</div>

<form action="<?= Adminko\System::selfUrl() ?>" method="post">
<?php   if (!$this->client) { ?>
    <label>Контактное лицо <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('purchase_person')) ?>" name="purchase_person" />
<?php if ($this->error['purchase_person']) { ?>
    <span class="error"><?= $this->error['purchase_person'] ?></span>
<?php } ?>
    <br/>
    <label>E-mail <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('purchase_email')) ?>" name="purchase_email" />
<?php if ($this->error['purchase_email']) { ?>
    <span class="error"><?= $this->error['purchase_email'] ?></span>
<?php } ?>
    <br/>
    <label>Телефон <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('purchase_phone')) ?>" name="purchase_phone" />
<?php if ($this->error['purchase_phone']) { ?>
    <span class="error"><?= $this->error['purchase_phone'] ?></span>
<?php } ?>
    <br/>
    <label>Адрес доставки <span class="require">*</span></label><br/>
    <textarea name="purchase_address"><?= $this->escape($this->fromRequest('purchase_address')) ?></textarea>
<?php if ($this->error['purchase_address']) { ?>
    <span class="error"><?= $this->error['purchase_address_text'] ?></span>
<?php } ?>
    <br/>
<?php   } else { ?>
    <label>Способ отгрузки</label><br/>
    <textarea name="purchase_shipping"><?= $this->escape($this->fromRequest('purchase_shipping')) ?></textarea>
<?php if ($this->error['purchase_shipping']) { ?>
    <span class="error"><?= $this->error['purchase_shipping'] ?></span>
<?php } ?>
    <br/>
<?php   } ?>
    <label>Комментарий</label><br/>
    <textarea name="purchase_comment"><?= $this->escape($this->fromRequest('purchase_comment')) ?></textarea>
<?php if ($this->error['purchase_comment']) { ?>
    <span class="error"><?= $this->error['purchase_comment'] ?></span>
<?php } ?>
    <br/>
    <input type="button" href="/cart" value="Изменить заказ" />
    <input type="submit" value="Отправить" />
</form>
<?php } else { ?>
<h2>Ваша корзина пуста.</h2>
<?php } ?>
