<h1>Корзина</h1>
<?php if ($this->getQuantity()) { ?>
<form class="cart-form" method="post" action="/cart/save">
    <table>
        <tr class="title">
            <td class="title name">
                Товар
            </td>
            <td class="title price">
                Цена
            </td>
            <td class="title quantity">
                Количество
            </td>
            <td class="title cost">
                Стоимость
            </td>
            <td class="title delete">
                Удалить
            </td>
        </tr>
<?php 		foreach ($this->get() as $item) { ?>
<?php 			$product = Adminko\Model\Model::factory('product')->get($item->id); ?>
        <tr>
            <td class="name">
                <div class="cart_image_container">
                    <img src="<?= $product->getProductImage() ?>/r/50/50" alt="<?= $product->getProductArticle() ?> - <?= $product->getProductTitle() ?>"/>
                </div>
                <div class="cart_title_container">
                    <a href="<?= $product->getProductUrl() ?>"><?= $product->getProductArticle() ?> <?= $product->getProductTitle() ?></a>
                </div>
            </td>
            <td class="price">
                <?= $item->price ?> 
            </td>
            <td class="quantity">
                <input type="hidden" value="<?= $item->price ?>" name="price[<?= $product->getId() ?>]"/>
                <input type="hidden" value="<?= $item->quantity ?>" name="quantity[<?= $product->getId() ?>]"/>
                
                <a href="" class="cart_dec" onclick="return decItem(this)"></a>
                <span class="quantity"><?= $item->quantity ?></span>
                <a href="" class="cart_inc" onclick="return incItem(this)"></a>
            </td>
            <td class="cost">
                <?= $item->quantity * $item->price ?> 
            </td>
            <td class="delete">
                <a href="/cart/delete/<?= $product->getId() ?>" onclick="return confirm('Вы уверены, что хотите удалить товар?')"><img src="/image/delete.png" /></a>
            </td>
        </tr>
<?php 		} ?>
        <tr class="total">
            <td class="total name">
                &nbsp;
            </td>
            <td class="total price">
                Итого:
            </td>
            <td class="total quantity">
                <?= $this->getQuantity() ?>
            </td>
            <td class="total cost">
                <?= $this->getSum() ?>
            </td>
            <td class="total delete">
                &nbsp;
            </td>
        </tr>
<?php if ($this->client) { ?>
        <tr class="discount">
            <td class="total name">
                &nbsp;
            </td>
            <td class="total price" colspan="2">
                Ваша скидка:
            </td>
            <td class="total cost">
                <?= round((1 - $this->discount) * 100) ?> %
            </td>
            <td class="total delete">
                &nbsp;
            </td>
        </tr>
        <tr class="final">
            <td class="total name">
                &nbsp;
            </td>
            <td class="total price" colspan="2">
                С учетом скидки:
            </td>
            <td class="total cost">
                <?= round($this->getSum() * $this->discount) ?>
            </td>
            <td class="total delete">
                &nbsp;
            </td>
        </tr>
<?php } ?>
    </table>
    <br/>
<?php if ($this->client) { ?>
    <input type="hidden" name="discount" value="<?= $this->discount ?>"/>
<?php } ?>
    <input type="button" href="javascript: history.back()" value="Продолжить покупки" style="margin-left: 70px;" />
    <input type="button" href="/cart/clear" confirm="Вы уверены, что хотите очистить корзину?" value="Очистить корзину" />
    <input type="button" href="/purchase" value="Оформить заказ" style="float: right;" />
</form>
<?php } else { ?>
<h2>Ваша корзина пуста.</h2>
<?php } ?>
