<?php if( $this->count > $this->by_page ) { ?>
<div class="pages">
    Страницы:
<?php 		foreach( $this->pages as $page ) { ?>
<?php 			if( $page['link'] ) { ?>
<a href="<?= $this->escape( $page['link'] ) ?>"><?php if ( $page['number'] ) { ?><?= $page['number'] ?><?php } else { ?>&hellip;<?php } ?></a>
<?php 			} else { ?>
<b><?= $page['number'] ?></b>
<?php 			} ?>
<?php		} ?>
</div>
<?php } ?>