<h1>Регистрация</h1>
<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    <label>Название компании <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('client_title')) ?>" name="client_title" />
<?php if ($this->error['client_title']) { ?>
    <span class="error"><?= $this->error['client_title'] ?></span>
<?php } ?>
    <br/>
    <label>E-mail <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('client_email')) ?>" name="client_email" />
<?php if ($this->error['client_email']) { ?>
    <span class="error"><?= $this->error['client_email'] ?></span>
<?php } ?>
    <br/>
    <label>Телефон <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('client_phone')) ?>" name="client_phone" />
<?php if ($this->error['client_phone']) { ?>
    <span class="error"><?= $this->error['client_phone'] ?></span>
<?php } ?>
    <br/>
    <label>Контактное лицо <span class="require">*</span></label>
    <input type="text" value="<?= $this->escape($this->fromRequest('client_person')) ?>" name="client_person" />
<?php if ($this->error['client_person']) { ?>
    <span class="error"><?= $this->error['client_person'] ?></span>
<?php } ?>
    <br/>
    <label>Юридический адрес <span class="require">*</span></label><br/>
    <textarea name="client_legal_address"><?= $this->escape($this->fromRequest('client_legal_address')) ?></textarea>
<?php if ($this->error['client_legal_address']) { ?>
    <span class="error"><?= $this->error['client_legal_address'] ?></span>
<?php } ?>
    <br/>
    <label>Фактический адрес</label><br/>
    <textarea name="client_actual_address"><?= $this->escape($this->fromRequest('client_actual_address')) ?></textarea>
<?php if ($this->error['client_actual_address']) { ?>
    <span class="error"><?= $this->error['client_actual_address'] ?></span>
<?php } ?>
    <br/>
    <input type="submit" value="Зарегистрироваться" />
</form>
<br/>
<a href="/client">Войти</a>
&nbsp;&nbsp;&nbsp;
<a href="/client/recovery">Забыли пароль?</a>
