<p>
Название компании: <?= $this->client->getClientTitle() ?><br/>
Email: <?= $this->client->getClientEmail() ?><br/>
Телефон: <?= $this->client->getClientPhone() ?><br/>
Контактное лицо: <?= $this->client->getClientPerson() ?><br/>
Юридический адрес: <?= $this->client->getClientLegalAddress() ?><br/>
Фактический адрес: <?= $this->client->getClientActualAddress() ?><br/>
</p>

<p>Перейти к редактированию пользователей <a href="http://bodysolid-europe.ru/admin/client">http://bodysolid-europe.ru/admin/client</a>.</p>
